-- WhatTheWhisper -- Emoticons, emoji and raid markers.
--
-- WoW ships no emoji glyphs in any font on any of the four clients, so the addon
-- carries its own atlas (Art/Emoji.tga, generated by Tools/gen_emoji.py) and
-- renders it through inline |T...|t markup, which every client supports.
--
-- What goes over the wire is always plain text -- ":)" or ":fire:" or "{rt1}" --
-- so the person on the other end sees something sensible whether or not they
-- have this addon.

local _, ns = ...
local Text, Draw = ns.Text, ns.Draw

local Emoticons = {}
ns.Emoticons = Emoticons

local find, sub, byte, lower = string.find, string.sub, string.byte, string.lower

--------------------------------------------------------------------------------
-- Tables
--------------------------------------------------------------------------------

-- ASCII emoticon -> emoji name. Longer sequences must be tried first, which is
-- why the scanner sorts by length.
Emoticons.ASCII = {
	[":)"] = "smile",   [":-)"] = "smile",   ["=)"] = "smile",  [":]"] = "smile",
	[":D"] = "grin",    [":-D"] = "grin",    ["=D"] = "grin",
	["xD"] = "laugh",   ["XD"] = "laugh",    ["xd"] = "laugh",
	[";)"] = "wink",    [";-)"] = "wink",
	[":P"] = "tongue",  [":-P"] = "tongue",  [":p"] = "tongue", ["=P"] = "tongue",
	["8)"] = "cool",    ["B)"] = "cool",     ["8-)"] = "cool",
	[":*"] = "love",    ["^^"] = "blush",    ["^_^"] = "blush",
	[":|"] = "neutral", ["-_-"] = "neutral",
	[":("] = "sad",     [":-("] = "sad",     ["=("] = "sad",
	[":'("] = "cry",    [";("] = "cry",
	[">:("] = "angry",  [">:-("] = "angry",
	[":O"] = "surprised", [":o"] = "surprised", [":-O"] = "surprised",
	[":/"] = "confused", [":\\"] = "confused", [":S"] = "confused", [":s"] = "confused",
	["zzz"] = "sleep",  ["Zzz"] = "sleep",
	["<3"] = "heart",   ["</3"] = "heart_broken",
}

-- Canonical text form for each emoji, used when the picker inserts one.
Emoticons.INSERT = {
	smile = ":)", grin = ":D", laugh = "xD", joy = ":joy:", wink = ";)",
	tongue = ":P", cool = "8)", love = ":*", blush = "^^", neutral = ":|",
	sad = ":(", cry = ":'(", angry = ">:(", surprised = ":O", confused = ":/",
	sleep = "zzz",
	heart = "<3", heart_broken = "</3", star = ":star:", sparkles = ":sparkles:",
	fire = ":fire:", skull = ":skull:", crown = ":crown:", sword = ":sword:",
	shield = ":shield:", potion = ":potion:", gem = ":gem:", coin = ":coin:",
	ok = ":ok:", no = ":no:", warn = ":warn:", question = ":question:",
}

Emoticons.CATEGORIES = {
	{
		id = "smileys", label = "Smileys",
		items = { "smile", "grin", "laugh", "joy", "wink", "tongue", "cool", "love",
			"blush", "neutral", "sad", "cry", "angry", "surprised", "confused", "sleep" },
	},
	{
		id = "symbols", label = "Symbols",
		items = { "heart", "heart_broken", "star", "sparkles", "fire", "skull",
			"crown", "sword", "shield", "potion", "gem", "coin",
			"ok", "no", "warn", "question" },
	},
	{
		id = "markers", label = "Markers",
		items = { "rt1", "rt2", "rt3", "rt4", "rt5", "rt6", "rt7", "rt8" },
	},
}

-- Raid target markers exist in every client and are already understood by every
-- player, so they are offered as a category of their own.
local MARKER_TEXTURE = "Interface\\TargetingFrame\\UI-RaidTargetingIcon_%d"
local MARKER_TAGS = {
	rt1 = 1, rt2 = 2, rt3 = 3, rt4 = 4, rt5 = 5, rt6 = 6, rt7 = 7, rt8 = 8,
	star = 1, circle = 2, coin = 2, diamond = 3, triangle = 4,
	moon = 5, square = 6, cross = 7, x = 7, skull = 8,
}
Emoticons.MARKER_TAGS = MARKER_TAGS

function Emoticons.MarkerMarkup(index, size)
	return string.format("|T" .. MARKER_TEXTURE .. ":%d:%d|t", index, size or 0, size or 0)
end

function Emoticons.MarkerTexture(index)
	return string.format(MARKER_TEXTURE, index)
end

--------------------------------------------------------------------------------
-- Scanner
--------------------------------------------------------------------------------

local asciiSorted
local function buildSorted()
	asciiSorted = {}
	for token in pairs(Emoticons.ASCII) do
		asciiSorted[#asciiSorted + 1] = token
	end
	table.sort(asciiSorted, function(a, b) return #a > #b end)
end

local function isWordByte(b)
	if not b then return false end
	return (b >= 48 and b <= 57) or (b >= 65 and b <= 90) or (b >= 97 and b <= 122) or b >= 128
end

local function replacement(name, style, size, colorEscape)
	if style == "images" then
		local markup = Draw.EmojiMarkup(name, size)
		if markup then return markup end
	end
	local textForm = Emoticons.INSERT[name]
	if not textForm then return nil end
	if style == "colored" then
		return colorEscape .. textForm .. "|r"
	end
	return nil
end

local function processChunk(chunk, style, size, colorEscape)
	if not asciiSorted then buildSorted() end
	local out, pos, last = nil, 1, 1
	local length = #chunk
	local markersOn = ns.db.profile.emoticons.raidMarkers

	while pos <= length do
		local matched, matchLen

		-- {rt1} / {skull} style raid markers
		if byte(chunk, pos) == 123 then       -- '{'
			local close = find(chunk, "}", pos + 1, true)
			if close and close - pos <= 12 and markersOn then
				local index = MARKER_TAGS[lower(sub(chunk, pos + 1, close - 1))]
				if index then
					matched = Emoticons.MarkerMarkup(index, size)
					matchLen = close - pos + 1
				end
			end
		end

		-- :name: style, the convention every chat app already uses
		if not matched and byte(chunk, pos) == 58 then    -- ':'
			local close = find(chunk, ":", pos + 1, true)
			if close and close - pos <= 16 then
				local key = sub(chunk, pos + 1, close - 1)
				if key ~= "" and find(key, "^[%a_]+$") and ns.EMOJI_ATLAS[key] then
					local rep = replacement(key, style, size, colorEscape)
					if rep then
						matched = rep
						matchLen = close - pos + 1
					end
				end
			end
		end

		-- ASCII emoticons, only when they stand on their own
		if not matched and not isWordByte(pos > 1 and byte(chunk, pos - 1) or nil) then
			for i = 1, #asciiSorted do
				local token = asciiSorted[i]
				if sub(chunk, pos, pos + #token - 1) == token then
					if not isWordByte(byte(chunk, pos + #token)) then
						local rep = replacement(Emoticons.ASCII[token], style, size, colorEscape)
						if rep then
							matched = rep
							matchLen = #token
						end
					end
					break
				end
			end
		end

		if matched then
			out = out or {}
			out[#out + 1] = sub(chunk, last, pos - 1)
			out[#out + 1] = matched
			pos = pos + matchLen
			last = pos
		else
			pos = pos + Text.CharBytes(chunk, pos)
		end
	end

	if not out then return chunk end
	out[#out + 1] = sub(chunk, last)
	return table.concat(out)
end

-- Converts emoticons in the plain-text parts of a message. Never touches item
-- links, textures or colour codes.
function Emoticons.Process(text, size)
	if not text or text == "" then return text end
	local style = ns.db.profile.emoticons.style
	local markers = ns.db.profile.emoticons.raidMarkers
	if style == "text" and not markers then return text end
	if not find(text, "[:;=<>%^%-{xXzZ8B]") then return text end

	local colorEscape = ns.Color.ToEscape(ns.Theme.Get("accent"))
	return Text.MapPlain(text, function(chunk)
		return processChunk(chunk, style, size or ns.Theme.FontSize("BODY"), colorEscape)
	end)
end

--------------------------------------------------------------------------------
-- Picker support
--------------------------------------------------------------------------------

function Emoticons.InsertText(name)
	local markerIndex = MARKER_TAGS[name]
	if name:match("^rt%d$") and markerIndex then
		return "{" .. name .. "}"
	end
	return Emoticons.INSERT[name] or (":" .. name .. ":")
end

function Emoticons.RememberRecent(name)
	local recent = ns.db.profile.emoticons.recent
	for i = #recent, 1, -1 do
		if recent[i] == name then table.remove(recent, i) end
	end
	table.insert(recent, 1, name)
	for i = #recent, 25, -1 do recent[i] = nil end
end
